### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by Yureien** [citysu/csiread#10]
Do you have any plans to implement support for this in the future? Alternatively, can you please guide me on how the code works, so that I am able to create a PR for it?

If needed, I can provide you the data from an ESP32.

**Comment by citysu** [comment]
Thans for your attention. I haven't decided to add this feature yet. I think `pandas.read_csv` may meet the requirements for esp32 data parsing, e.g. flexibility and performance. Later, I will add an example about it

The design can be found in `docs/`, The library uses `Cython` to improve the performance and `numpy` is the only runtime dependency.
