### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CSIhicham** [citysu/csiread#18]
Hello,

I have a problem when I execute this command pip3 install csiread, 
[](url)
![2022-01-20 17_54_43-2022-01-20 17_53_35-Greenshot png - Visionneuse de photos Windows](https://user-images.githubusercontent.com/96484184/150385326-86775c47-c9d5-4755-b0d3-8bfc8b551a3e.png)

Any help!
Thanks

**Comment by citysu** [comment]
Your python version is too low. Please install csiread from source, or install python 3.6+ via anaconda

**Comment by CSIhicham** [comment]
> Hello,
> 
> I have a problem when I execute this command pip3 install csiread, ![2022-01-20 17_54_43-2022-01-20 17_53_35-Greenshot png - Visionneuse de photos Windows](https://user-images.githubusercontent.com/96484184/150385326-86775c47-c9d5-4755-b0d3-8bfc8b551a3e.png)
> 
> Any help! Thanks
