### ISSUE TITLE
live spectogram of CSI

### ISSUE THREAD

**Issue by shuchi-seki** [citysu/csiread#27]
Hi Citysu,

Thank you so much for sharing the process. I have followed your process and got the following live CSI spectogram. I am using Atheros, ubuntu 20.04 and Tplink-WDR4300 and working with 20MHz. 

My question is, I cannot understand why am I not seeing all four color spectrums? Also, when I am printing CSI values, it's matrix wrapped in another matrix. How can i view them in a tabular form so that I can understand each column or row? Please, help. I am new in this . Thnaks.
![20220920_125136](https://user-images.githubusercontent.com/99450304/191631053-a80f3421-4d3b-4ee5-bf4c-911f3a6e8810.jpg)
![20220920_192438_HDR](https://user-images.githubusercontent.com/99450304/191631070-0ca0e920-6558-46f9-929d-2d5d0438233a.jpg)

**Comment by kr689** [comment]
Hi,

I'm using a similar set up to you.I could not find the function  that enables the real-time viewing of the spectogram for Atheros. There is an example there for Intel, and nexmon but not Atheros. Where did you get yours?
