### ISSUE TITLE
Can‘t find wheel files

### ISSUE THREAD

**Issue by sarielkk** [citysu/csiread#31]
I can't find wheel files in Github-Actions-Artifacts: csiread_dist. There is nothing in Github-Actions though I fork the latest version. 
I use python3.9.

**Comment by sarielkk** [comment]
When I use python3.10, it doesn't work, either.
![image](https://github.com/citysu/csiread/assets/52898164/5e433fb0-27bf-4a62-af34-4352fda9ed35)

**Comment by citysu** [comment]
You can replace `Cython>=0.29` with `Cython>=0.29,<3.0` in requirements.txt, or replace `__pcapheader` with `pcapheader` in csiread.pyx and csiread.pxd for Cython >= 3.0.
