### ISSUE TITLE
csiviewer for nexmon

### ISSUE THREAD

**Issue by GuoJingtao-1997** [citysu/csiread#8]
Hi Thank you so much for your great job. I saw that currently you only support intel and athero in csiviewer.py. Will there be a plan to support nexmon latter? Thank you so much in advance.

**Comment by citysu** [comment]
Yes, I plan to use Nexmon.pmsg (udp package) instead of Nexmon.pmsg (raw package) in version 1.3.7. The corresponding examples will be adjusted  including csiserver.py, csiviewer.py. etc. But I'm busy with other works recently. I'm not sure when to continue these.

**Comment by GuoJingtao-1997** [comment]
Cool! Looking forward to see it. I may also try to do this when I am free hhh. Thank you so much again for this great job!
