### ISSUE TITLE
AttributeError: module 'csiread' has no attribute 'ESP32'

### ISSUE THREAD

**Issue by arcgolatkar** [citysu/csiread#9]
I checked the csireadESP32.py from examples and while running this file with my local data collected using ESP32 -CSI tool, I am getting the following error: 
AttributeError: module 'csiread' has no attribute 'ESP32'
Wanted to know whether I can plot my data in real-time using this library?

**Comment by citysu** [comment]
This library doesn't support esp32-csi-tool. I don't have any esp32 devices and cannot guarantee that csiread.ESP32 is correct, so I just added the original implementation about it in the examples
